### ISSUE TITLE
Major Performance Concerns

### ISSUE THREAD

**Issue by danbopes** [SOBotics/AdvancedFlagging#34]
As of late, I've had to disable AdvancedFlagging because of the delay added in my normal routine. At certain points, I've noticed 10+ second delays while my status bar reads "Waiting for tampermonkey". As soon as I disable AdvancedFlagging, this went away.

I have a sneaking suspicion, that there is some type of cache that when grows is causing these delays. When I uninstalled AdvancedFlagging and re-enabled it, the issues seemed to go away for roughly a few days. Sorry this ticket is a bit broad, if you don't have time to look into it, when I get more free time I can dig into this a bit more.

**Comment by rjrudman** [comment]
Hmm. I'm surprised re-installing the script would have an effect, as uninstalling doesn't actually clear any cache it uses. 

When it's slow again, can you try to go into configuration (bottom right of any SE page) and click 'Clear expired items from cache'? Does that have any impact?

What version are you currently running?

**Comment by rjrudman** [comment]
This has been a recurring issue, and I'm not really sure exactly what's causing it. 

The last major release, I toned down the aggressiveness of the caching, and moved the cross-site caching to use greasemonkey/tampeymonkey APIs instead. This did provide a significant speed increase, so I'm curious what's causing it now.

Does this only happen on page load? Or does it sometimes happen after interacting with the page? It *might* also be caused by a problematic connection when it's querying metasmoke and napi

**Comment by rjrudman** [comment]
@danbopes @Filnor I've updated all dependencies and now target esnext. This *might* have an impact here. Could you see if there's any improvement?

**Comment by Filnor** [comment]
@rjrudman Haven't it tested it exteremely in-depth, it seems a bit faster and I haven't experienced any slowdown except a hanging and then crashing TM after clearing the expired items.

**Comment by sri-shree** [comment]
I update AF today and looks much better. Hope new change solve the problem and no need to uninstall / install again after week. :)

**Comment by danbopes** [comment]
Can we just remove the caching? This is clearly the cause of the issue: And it doesn't really seem like the caching saves really anything. Most pages we visit once, and then we'll never go to them again. We're just caching a ton of data, that in the end, is going to be useless.

**Comment by Filnor** [comment]
+1 On removing the caching. I forgot to update, but the issues remain the same, they were just not that regular as before. But there are still random slowdowns on completely unrelated sites like MSO (can we please remove site-metas from AF? AFAIK, no bot ever has reported a post from there) or loadinh the inbox/achievements. Also it sometimes happened when browsing other sites (e.g. Microsoft TechNet).

Also clearing the Cache is just terrible. The best solution for me currently is purging everything cached. There should be a button for that.

Furthermore, maybe make it possible to enable/disable caching from the settings?

**Comment by rjrudman** [comment]
@danbopes @Filnor There's an experimental branch here: https://github.com/SOBotics/AdvancedFlagging/tree/experimental_caching/dist which disables caching entirely. It breaks a few things like showing the red flag to indicate it's been flagged, but there's no way to keep that without caching it somewhere.

Are you able to give that version a go and see if it improves performance?

**Comment by sri-shree** [comment]
@rjrudman Can you push z-index fix on that experimental branch.

**Comment by rjrudman** [comment]
@sri-shree Done! You will need to manually force an update, as I'm unable to easily change the version numbers without breaking things.

Uninstall the script and re-install it

**Comment by danbopes** [comment]
Currently on the experimental branch: Smoke Detector/Metasmoke aren't working at all, and I can't save any settings. If I click on a checkbox, hit save, it just refreshes, and none of the checkboxes stay checked.

**Comment by Filnor** [comment]
I can repro the settings issue, but MS/SD works fine for me as long MS is up.

**Comment by iBug** [comment]
Title: **Extreme CPU usage**

I spent more than a month, re-installed Windows 10 twice, re-installed Chrome fresh 4+ times and Tampermonkey 6+ times, before finally tracking down this userscript. Previously I suspected a lot of Charcoal userscripts, as well as AutoComment, Magic Editor and cv-pls Request Generator.

I'll cut the cucumber and go with my setup directly:

# Environment

- Windows 10 64-bit (from 1703 to 1809 - makes no difference)
- Chrome 67 to 71 (all, also makes no difference)
- Tampermonkey 4.6 and 4.7 (didn't test 4.5, but I briefly recall it was fine? or maybe I didn't install AF at that point?)

# Phenomena

As said in the first comment of this thread, `Waiting for extension Tampermonkey ...` blocks the page for 10+ seconds. Also, since I'm on a laptop, the fan goes noisy and I can see a long-time CPU hog (80%+ for 40+ seconds, Core i7-8750H), making the SO page almost irresponsive. In F12 Developer Console, I see no message related to AF (at least none of them led me into suspecting AF).

Any ideas? I think it's highly related (In case you're on a desktop, sudden CPU hogging would probably be less noticeable, especially when you're using water-cooling)

**Comment by Filnor** [comment]
@iBug Yes. I monitored the same CPU hog when Chrome waits for AF. For me it happens randomly and kinda not reproduceable, but mostly on SE network sites ans especially SO. My Specs are also fairly decent (i7-8700K and 32 GB of DDR4 RAM, so it's clearly not my system)

**Comment by rjrudman** [comment]
@iBug Are you able to give the experimental branch a whirl? I've attempted to fix the performance multiple times, to no avail. It does appear to be an issue with caching and having it written/read from disk *far* more often than it need be.

It's a little buggy (settings won't save), but if it's solving performance issues for everyone, I'll try to find a few hours to properly remove caching where not needed

**Comment by rjrudman** [comment]
@danbopes Are you still experiencing this? The MS keys should be cached, even on the experimental branch

**Comment by iBug** [comment]
@rjrudman Forgot to update here. I tried the experimental branch and it's been working all OK: No lagging, no CPU hogging. Thanks

**Comment by rjrudman** [comment]
@iBug @Filnor @ShreeKhanal @danbopes Caching has been removed completely from AF. The exceptions are for configuration and metasmoke keys. Please let me know if there are any issues. One thing that will be missing entirely is the red flag indicating the post had been flagged - there's no way to keep that without caching. New version is [1.2.0](https://github.com/SOBotics/AdvancedFlagging/blob/master/dist/AdvancedFlagging.user.js)

**Comment by rjrudman** [comment]
Also - sorry for the long delay in this, have been quite busy

**Comment by danbopes** [comment]
How much caching is used for the flag dialog? Looking at generic bot's caching, it was caching every post in each page. If we're only caching one post, on click afterwards, I don't think the cache would be hit too hard. I believe the amount of time the cache was being updated was the issue (Sometimes 4+ times on one page load).
